name: 'Auto Release Draft'
description: 'Drafts a GitHub release with the changes introduced by newly created crated version tag.'
author: 'Fallon Rohllf'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN used to authenticate the current repository'
    required: true
outputs:
  release-url:
    description: 'The URL of the GitHub release that was drafted'
runs:
  using: 'node12'
  main: 'dist/index.js'
